### PyTorch Fundamentals

#### Set up
**We'll import PyTorch and set seeds for reproducibility. Note that PyTorch also required a seed since we will be generating random tensors.**

In [1]:
import numpy as np
import torch

In [2]:
#Setting the seed
SEED = 1234

In [3]:
# Set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

#### Basics
- We'll first cover some basics with PyTorch such as creating tensors and converting from common data structures (lists, arrays, etc.) to tensors.

In [4]:
#Create a random tensor

x = torch.randn(2,3) # normal distribution (rand(2,3) -> uniform distribution)

print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

Type : torch.FloatTensor

Size: torch.Size([2, 3])

Values : 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [6]:
#Create a random tensor
y = torch.randn(3,3) # normal distribution (rand(2,3) -> uniform distribution)

print(y.type())
print('')
print(y.shape)
print('')
print(y)

torch.FloatTensor

torch.Size([3, 3])

tensor([[ 0.8848, -0.2611,  0.6104],
        [-0.0098, -1.4473, -0.2039],
        [ 0.8738, -0.6816,  0.6339]])


In [7]:
#Zeros Tensor

x = torch.zeros(3,3)
print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

Type : torch.FloatTensor

Size: torch.Size([3, 3])

Values : 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
#Ones Tensor
x = torch.ones(3,3)
print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

Type : torch.FloatTensor

Size: torch.Size([3, 3])

Values : 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# List → Tensor

x = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

Type : torch.FloatTensor

Size: torch.Size([3, 3])

Values : 
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [10]:
# NumPy array → Tensor

x = torch.Tensor(np.random.rand(2,4))
print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")


Type : torch.FloatTensor

Size: torch.Size([2, 4])

Values : 
tensor([[0.1915, 0.6221, 0.4377, 0.7854],
        [0.7800, 0.2726, 0.2765, 0.8019]])


In [11]:
# Changing tensor type
print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

x= x.int()

print(f"Type : {x.type()}")
print('')
print(f"Size: {x.shape}")
print('')
print(f"Values : \n{x}")

Type : torch.FloatTensor

Size: torch.Size([2, 4])

Values : 
tensor([[0.1915, 0.6221, 0.4377, 0.7854],
        [0.7800, 0.2726, 0.2765, 0.8019]])
Type : torch.IntTensor

Size: torch.Size([2, 4])

Values : 
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


### Operations
- Now we'll explore some basic operations with tensors.

In [21]:
# Addition

x = torch.randint(0,5,(3,3))
print(f"Values : \n{x}")
print('')

y = torch.randint(0,8,(3,3))
print(f"Values : \n{y}")
print('')

sum = x + y
print(f"Type : {sum.type()}")
print('')
print(f"Size: {sum.shape}")
print('')
print(f"Values : \n{sum}")

Values : 
tensor([[3, 1, 1],
        [0, 2, 0],
        [4, 3, 0]])

Values : 
tensor([[0, 0, 5],
        [1, 0, 6],
        [3, 1, 1]])

Type : torch.LongTensor

Size: torch.Size([3, 3])

Values : 
tensor([[3, 1, 6],
        [1, 2, 6],
        [7, 4, 1]])


In [27]:
# Dot product
x = torch.randint(0,5,(3,3))
print(f"Values : \n{x}")
print('')

y = torch.randint(0,8,(3,2))
print(f"Values : \n{y}")
print('')

product = torch.mm(x,y)
print(f"Type : {product.type()}")
print('')
print(f"Size: {product.shape}")
print('')
print(f"Values : \n{product}")

Values : 
tensor([[2, 4, 0],
        [1, 1, 0],
        [2, 0, 3]])

Values : 
tensor([[1, 4],
        [2, 3],
        [1, 2]])

Type : torch.LongTensor

Size: torch.Size([3, 2])

Values : 
tensor([[10, 20],
        [ 3,  7],
        [ 5, 14]])


In [30]:
# Transpose
product_T = torch.t(product)
print(f"Type : {product_T.type()}")
print('')
print(f"Size: {product_T.shape}")
print('')
print(f"Values : \n{product}")
print('')
print(f"Values : \n{product_T}")

Type : torch.LongTensor

Size: torch.Size([2, 3])

Values : 
tensor([[10, 20],
        [ 3,  7],
        [ 5, 14]])

Values : 
tensor([[10,  3,  5],
        [20,  7, 14]])


In [35]:
# Reshape
x = torch.randn(2,3)
print(f"Values : \n{x}")
print('')
z = x.view(6,1)
print(f"Type : {z.type()}")
print('')
print(f"Size: {z.shape}")
print('')
print(f"Values : \n{z}")

Values : 
tensor([[ 0.9020,  0.9087,  1.0404],
        [-0.6150,  0.9251, -0.2355]])

Type : torch.FloatTensor

Size: torch.Size([6, 1])

Values : 
tensor([[ 0.9020],
        [ 0.9087],
        [ 1.0404],
        [-0.6150],
        [ 0.9251],
        [-0.2355]])


In [36]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])



In [37]:
a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])



In [38]:
b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])



In [39]:
c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [45]:
# Dimensional operations
x = torch.randint(0,10,(2, 3))
print(f"Values: \n{x}")
print('')
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
print('')
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[1, 0, 4],
        [8, 4, 4]])

Values: 
tensor([9, 4, 8])

Values: 
tensor([ 5, 16])


### Indexing
- Now we'll look at how to extract, separate and join values from our tensors.

In [52]:
# Dimensional operations
x = torch.randint(0,10,(2, 3))
print(f"Values: \n{x}")
print('')
print(f"x[:1]: \n{x[:1]}")
print('')
print(f"x[:2]: \n{x[:2]}")
print('')
print(f"x[:1, 1:3]: \n{x[:1, 0:2]}]")

Values: 
tensor([[6, 3, 3],
        [4, 9, 9]])

x[:1]: 
tensor([[6, 3, 3]])

x[:2]: 
tensor([[6, 3, 3],
        [4, 9, 9]])

x[:1, 1:3]: 
tensor([[6, 3]])]


### Slicing

In [58]:
# Dimensional operations
x = torch.randint(0,10,(3, 3))
print(f"Values: \n{x}")
print('')

col_indces = torch.LongTensor([0,2])
chosen = torch.index_select(x, dim = 1, index=col_indces)# values from column 0 & 2
print(f"Values: \n{chosen}")

Values: 
tensor([[4, 6, 5],
        [4, 7, 8],
        [3, 9, 1]])

Values: 
tensor([[4, 5],
        [4, 8],
        [3, 1]])


In [59]:
row_indices = torch.LongTensor([0,2])
col_indces = torch.LongTensor([0,1])

chosen = x[row_indices, col_indces] # values from (0, 0) & (1, 2)
print(f"Values: \n{chosen}")

Values: 
tensor([4, 9])


### Joining

In [60]:
# Dimensional operations
x = torch.randint(0,10,(2, 2))
print(f"Values: \n{x}")
print('')

Values: 
tensor([[4, 2],
        [5, 7]])



In [62]:
# Concatenation
y = torch.cat([x, x], dim=1) # concat on a specified dimension
print (y)
print (y.shape)

tensor([[4, 2, 4, 2],
        [5, 7, 5, 7]])
torch.Size([2, 4])


In [63]:
# Stacking

z = torch.stack([x,x], dim = 0)
print (z)
print (z.shape)

tensor([[[4, 2],
         [5, 7]],

        [[4, 2],
         [5, 7]]])
torch.Size([2, 2, 2])


### Gradients
*We can determine gradients (rate of change) of our tensors with respect to their constituents using gradient bookkeeping. The gradient is a vector that points in the direction of greatest increase of a function. We'll be using gradients in the next lesson to determine how to change our weights to affect a particular objective function (ex. loss).*

In [65]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 3, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print(f"x: \n{x}")
print('')
print(f"y: \n{y}")
print('')
print(f"z: \n{z}")
print('')
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.2223, 0.2539, 0.8482],
        [0.0727, 0.6497, 0.9484],
        [0.1678, 0.0592, 0.7710]], requires_grad=True)

y: 
tensor([[2.6669, 2.7617, 4.5447],
        [2.2181, 3.9491, 4.8451],
        [2.5033, 2.1775, 4.3128]], grad_fn=<AddBackward0>)

z: 
3.331031560897827

x.grad: 
tensor([[0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333],
        [0.3333, 0.3333, 0.3333]])


### CUDA
*We also load our tensors onto the GPU for parallelized computation using CUDA (a parallel computing platform and API from Nvidia).*

In [66]:
# Is CUDA available?
print (torch.cuda.is_available())

False


In [67]:
# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cpu
